ALTER TABLE USERS
    ALTER COLUMN role SET NOT NULL;
ALTER TABLE USERS
    ALTER COLUMN department SET NOT NULL;
ALTER TABLE USERS
    ALTER COLUMN bio SET NOT NULL;
ALTER TABLE USERS
    ALTER COLUMN contact SET NOT NULL;