ALTER TABLE USERS ALTER COLUMN role DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN department DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN bio DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN contact DROP NOT NULL;